# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now we have gathered all the required skills needed to solve systems of linear equations. We saw why need to calculate inverses of matrices, followed by matrix multiplication to figure the values of unknown variables. 

Following exercises present some problems that can be converted into a system of linear equations. Solve the problems for the values of unknown variables. 

## Objectives
You will be able to:

* Build a system of equations from given problem by creating matrix and vectors in NumPy
* Calculate the inverse and dot-product to get the values for unknown variables.
* Solve linear equations using `numpy.linalg.solve()`

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea was sold, giving a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [34]:
# Solution:
import numpy as np
day_1 = np.array([29,41])
day_1_cost = np.array([490])
day_2 = np.array([23,41])
day_2_cost = np.array([448])

A = np.array([day_1, day_2])
B = np.array([day_1_cost, day_2_cost])

inverse = np.linalg.inv(A)

res1 = inverse.dot(B)
res2 = np.linalg.solve(A, B)

print("\n", res1, "\n\n", res2)


 [[7.]
 [7.]] 

 [[7.]
 [7.]]


In [24]:
# Explain your answer in terms of prices
# Both the tea and the coffee cost 7 dollars

## Exercise 2:

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in another music concert. 

How much was the admission for each child and adult?

In [36]:
# Create a system of equations
cost_1 = np.array([162])
party_1 = np.array([12,3])
cost_2 = np.array([122])
party_2 = np.array([8,3])


A = np.array([party_1, party_2])
B = np.array([cost_1, cost_2])

inverse = np.linalg.inv(A)

res1 = inverse.dot(B)
res2 = np.linalg.solve(A, B)

print("\n", res1, "\n\n", res2)

# system of equations
# 162 = 12*a + 3*b
# 122 = 8*a + 3*b
# 40 = 4*a => a = 10, plug back into the top equation
# 162 = 120 + 3b => 42 = 3b => b = 14
# check for the last one
# 122 = 8*10 + 3*14 = 80 + 42 = 122 thus (a, b) = (10,14)




 [[10.]
 [14.]] 

 [[10.]
 [14.]]


In [27]:
# Describe your result
# The price for an kids for these concerts were 10 dollars per person, but adults were a bit higher 
# at 14 dollars per person

## Exercise 3:

You want to make a certain kind of tropical punch, using bananas, oranges, and papayas. 

Suppose you don't know how many of each to put in the punch, but you know that there are seven pieces of fruit in the mix, and there are twice as many oranges as bananas. 

You also know that the seven pieces of fruit cost \$5.25, 

where bananas cost \$.50 each, oranges cost \$.75 each, and papayas cost \$1.25 each.

How many bananas, oranges and papayas would you need to make this punch ?

In [67]:
# Create a system of equations
total_fruit = 7

b = 1*.50
o = 2*b*.75
p = 1.25

total_cost = 5.25

A = np.matrix([[.75, .50, 1.25],[1,1,1], [1,-2,0]])
B = np.matrix([[5.25], [7], [0]])

inverse = np.linalg.inv(A)

res1 = inverse.dot(B)
res2 = np.linalg.solve(A, B)

print("\n", res1, "\n\n", res2)



 [[4.]
 [2.]
 [1.]] 

 [[4.]
 [2.]
 [1.]]


# Explain your answer

The first row is comparing the price, the second row is comparing the total number of fruits, the last row was comparing the relationship between each fruit.

There are 4 oranges, 2 bananas, and one papaya



## Exercise 4

A landlord owns 3 houses, a 1-bedroom, a 2-bedroom , and a 3-bedroom house. 

The total rent he receives is 1240 dollars. 

He needs to make some repairs, where it costs 10% of the 1-bedroom house’s rent for its repairs, 20% of the 2-bedroom for its repairs, and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was $276. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [3]:
# Create a system of equations
total_rent = 1240

b_1 = 1*.50
 = 2*b*.75
p = 1.25

total_cost = 5.25

A = np.matrix([[.75, .50, 1.25],[1,1,1], [1,-2,0]])
B = np.matrix([[5.25], [7], [0]])

inverse = np.linalg.inv(A)

res1 = inverse.dot(B)
res2 = np.linalg.solve(A, B)

print("\n", res1, "\n\n", res2)

In [11]:
# Explain your answer


## Summary
In this lab, we saw how to use Numpy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `.solve()`. We shall now take these skills forward and see how we can define a simple regression problem using linear algebra and solve it with numpy, only using the skills that we have learnt so far. 